### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by namemute** [mmunhappy/ICASSP2025-PDM#2]
Hello, author. I noticed that in the paper, the CA and SA of the MFGM module are connected in parallel. However, I found in the code that CA and SA are connected in series. Could you please explain this? Thank you.
![5GF8V66N1@J87FDJPUM4J7W](https://github.com/user-attachments/assets/5474b319-a156-4b7b-b5d1-c3707cb31976)
![BR53U~JS_EREF2~ZL%~2_XG](https://github.com/user-attachments/assets/58525379-0dd4-44f0-b2bf-295cb761695b)

**Comment by mmunhappy** [comment]
Yes, the parallel didn't work as well as the serial, we forgot to change what was in the picture, and we will rework the final version of the paper after that.
